### PR TITLE
Update to Boolector 3.2.1

### PR DESCRIPTION
**Pull request by inspier**
Bumps the version of Boolector to 3.2.1.

### CODE REVIEW

**Comment by fatemender** [comment]
Thank you @inspier for this update.  Would you like to be added to the crate authors and/or LICENSE file?

**Comment by inspier** [comment]
Sure that would be appreciated.

**Comment by inspier** [comment]
Yes that would be appreciated.

**Comment by fatemender** [comment]
I've added a copyright line in ee82a41795058d84949676bdee85896c149fde6b.  Does that look OK to you?

**Comment by inspier** [comment]
Yes thanks a lot.

**Pull request merged**
